# Generated by Django 4.2.5 on 2024-09-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("capitan", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True)),
                ("jugadores", models.CharField(max_length=200)),
                ("activo", models.BooleanField(default=False)),
            ],
        ),
    ]
